opnsynid_payment_instruction_aeroo_report
open-synergy/opnsynid-accounting-report pull request #67
Opened 2017-01-19 11:13 UTC by mikevhe18

2017-01-19 23:36 UTC, andhit-r requested changes

2017-01-19 23:36 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +                            WHEN C.date_maturity NOTNULL
Gunakan IS NOT NULL, NOTNULL tidak standard menurut https://www.postgresql.org/docs/9.1/static/functions-comparison.html

2017-01-19 23:36 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +                            WHEN C.date NOTNULL
Gunakan IS NOT NULL, NOTNULL tidak standard menurut https://www.postgresql.org/docs/9.1/static/functions-comparison.html

2017-01-19 23:36 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_lines.py
> +        digits=(16, 2)
Tidak usah pakai param digits

2017-01-19 23:36 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +        store=True
Jangan lupa dihapus kalau sudah selesai testnya

2017-01-20 03:34 UTC, andhit-r requested changes

2017-01-20 03:34 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/__openerp__.py
> +    "name": "Payment Instruction",
Payment Instruction Aeroo Report

2017-01-20 03:34 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +    def _get_date(self):
Fungsi ini buat apa?

2017-01-20 03:34 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +        store=True
Mike ini kok di store?

2017-01-20 07:58 UTC, mikevhe18 commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +    def _get_date(self):
ini fungsi buat munculin data date di reportnya mas

2017-01-22 02:23 UTC, andhit-r commented on opnsynid_payment_instruction_aeroo_report/reports/account_payment_instruction_helper.py
> +    def _get_date(self):
Kok pake fungsi lagi mike? Kan field date di object helper udah ada di https://github.com/open-synergy/opnsynid-accounting-report/pull/67/files#diff-5fb54bec5b45fd078e8ef1822e2a005dR38

Lo kan dah punya field date dari SQL

2021-05-14 23:15 UTC, closed without merging